---
output:
  pdf_document: default
  html_document: default
---
#01
<!-- 
Object x <-1:15 
Construct a 5x3 matrix for the value of x. 
-->
# Program
  x <- 1:15
  result_matrix <- matrix(x, nrow = 3, ncol = 5)
  print(result_matrix)





#02
<!-- 
Write a program to generate the following 4x4 matrix 
  0 0 0 0
  0 0 0 0
  0 0 0 0
-->
# Program
  A <- matrix(0, nrow = 4, ncol = 4)
  print(A)





#03
<!-- 
The object x<-1:8
Write a program to generate the following 3x8 matrix using "cbind(),rbind(),rev(),rep()"
  1 2 3 4 5 6 7 8
  8 7 6 5 4 3 2 1
  3 3 3 3 3 3 3 3
-->
# Program
  x <- 1:8
  cbind(unname(x), rev(x),rep(3,8))
  




#04
<!--
Chose two different(x,y) 4x4 matrix to perform the following arithmetic operations
  (a). x + y
  (b). x - y
  (c). x*y
  (d). x%*%y
  (e). Difference between (c) &(d)
  (f). Inverse of y
  (g). z<-x/y
  (h). Transpose of z
  (i). Diagonal of transpose matrix
-->
# Program
  x <- matrix(c(5, 10, 20, 30, 40, 50, 60, 70), ncol = 4, nrow = 4)
  y <- matrix(c( 1,  2,  3,  4, 5, 6, 7, 8), ncol = 4, nrow = 4)
## (a). x + y
  print(x + y)
## (b). x - y
  print(x - y)
## (c). x * y
  print(x * y)
## (d). x%*%y
  print(x %*% y)
## (e). difference between (c) & (d)
  ### 1. (c). Multiplication of each element of matrix(x) and matrix(y)
  ### 2. (d). Multiplication of matrix(x) and matrix(y)
## (f). Inverse of y
  require(MASS)
  print(ginv(y))
# (g). z<-x/y
  print(z <- x/y)
# (h). Transpose of z
  print(t(z))
# (i). Diagonal of transpose matrix
  print(diag(t(z)))





#05
<!-- 
Difference between (i) & (ii) 
  (i). x<-matrix(x<-1:9,3,3,byrow = TRUE) (ii). x<-matrix(x<-1:9,3,3)
-->
## Create Matrix(x) byrow=TRUE indicates that the matrix should be filled by rows.
  x <- matrix(x<-1:9,3,3,byrow = TRUE)
## Create matrix(x1) indicates that the matrix should be filled by columns (the default) or byrow=FALSE.
  x1 <- matrix(x<-1:9,3,3)
## print output
  print(x)
  print(x1)





#06
<!-- Which function can we use for inner product and outer product in matrix calculation? -->
## %*% is a function that used for inner product in matrix calculation.
# Program
  b <- matrix(c(1,2,3),nrow=3)
  bt <- matrix(c(1,2,3),nrow=1)
  b%*%bt
## %o% is a function that used for outer product in matrix calculation. 
# Program
  b <- matrix(c(1,2,3),nrow=3)
  bt <- matrix(c(1,2,3),nrow=1)
  b%o%bt






#07
<!-- Explain the use of all.equal() function in Matrix with a sample program. -->
## all.equal() function is the function that used to compare R objects.If they are different, comparison is still made to some extent, and a report of the differences is returned.
### Program
  x <- 1
  y <- 'String'
  print(all.equal(x,y))





#08
<!-- Explain the use of dim() function with a sample program. -->
## dim() function in R Language is used to get or set the dimension of the specified matrix, array or data frame.
### Program
  H <- matrix(1:6, 2,3)
  dim(H)
  print(H)
  
  
  


  
#09
<!-- Use of $ operator, and square brackets [] in List with example program. -->
## $ operator in list is used to access the element in the list by name.
## square brackets [] in List is used to access the element in the list by index.
# Program
  my_list <- list(username='Vuthy', age=21, year=4)
## Access with $ operator
  my_list$username
  my_list$age
  my_list$year
## Access with square brackets []
  my_list[1]
  my_list[2]
  my_list[3]






#10
<!-- Explain ifelse() with example. -->
a <- c(5,3,6,8,0,1)
ifelse(a %% 2 == 0, "even", "odd")




#11
<!-- 
Write a program to get the weight and height from the user to calculate the following cases
  a. If your BMI is less than 18.5, it falls within the underweight range.
  b. If your BMI is 18.5 to <25, it falls within the normal.
  c. If your BMI is 25.0 to <30, it falls within the overweight range.
  d. If your BMI is 30.0 or higher, it falls within the obese range.
-->
# Program
  w <- as.numeric(readline(prompt="Enter weight(kg): "))
  h <- as.numeric(readline(prompt="Enter height(m): "))
  bmi <- w/h^2
  if(bmi<18.5){
      print("underweight range")
  }else if (bmi<25) {
      print("normal range")
  }else if (bmi<30) {
      print("overweight range")
  }else{
      print("obese range")
  }
  



#12
<!-- Difference between List and Data frame with an example program. -->
## List is the array of element of same or different type that store in sequence.
## Data Frame is the matrix of the same or different type that store in the form of row and column.
# Program
## List
  a <- 1:5
  list(a)
## Data Frame
  weight <- c(60, 70, 80, 90)
  height <- c(1.67, 1.70, 1.65, 1.68)
  data.frame(Weight = weight, Height = height)





#13
<!-- Difference between repeat and while loop with example program. -->
## Repeat is the loop that requires you to explicitly break the loop on your own and can be at any point in the body of the loop.
## While is the loop that tests a condition to determine when to finish looping.
# Program
## Repeat loop
  i <- 1
  repeat {if (i==10) break;print(i);i<-i+1}

## While Loop
i <- 1
while (i<10) {print(i);i<-i+1}
